package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Bla1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Bla1() {
    }

}
